feat: add renderingThumbnails module
htmlacademy-javascript/2266613-kekstagram-30 pull request #6
Opened 2023-10-31 19:37 UTC by ivanfilippovw

2023-10-31 20:08 UTC, kenakula requested changes
Да, пока это все, продолжение в следующем разделе, нужно будет оживить модалку для этих превьюшек

2023-10-31 20:08 UTC, kenakula commented on js/main.js
> +import '../js/renderingThumbnails';
импортировать лучше только лишь функцию, которая будет запускать все остальные действия

2023-10-31 20:08 UTC, kenakula commented on js/renderingThumbnails.js
> +  newPicture.querySelector('.picture__comments').textContent = comments;
тут тебе в элементе нужно вписать количество комментариев, ты сейчас туда прокидываешь массив с объектами

2023-10-31 20:08 UTC, kenakula commented on js/renderingThumbnails.js
> +const similarPictures = getPhotosDescription();
у тебя приходит данных - массив из 25 объектов, в сетке 26 ячеек, поэтому нет у последнего никакого изображения 
![image](https://github.com/htmlacademy-javascript/2266613-kekstagram-30/assets/51047679/be9d1f1f-5c81-4da1-8edc-28822f538e13)

2023-10-31 20:08 UTC, kenakula commented on js/renderingThumbnails.js
> +export {};
пустые экспорты не оставляй, создай функцию с функционалом и экспортируй ее

2023-11-01 06:49 UTC, ivanfilippovw commented on js/renderingThumbnails.js
> +const similarPictures = getPhotosDescription();
ну там вроде по заданию предыдущему должно быть именно 25, поэтому так оставил, это неправильно? как раз если на 26 меняю константу в data.js, тоже 26я уже не грузится картинка

2023-11-01 08:04 UTC, kenakula approved these changes

2023-11-01 08:33 UTC, merged